language: node_js
node_js:
- 8
deploy:
  provider: npm
  email: charlie@bowtie.co
  skip_cleanup: true
  on:
    tags: true
    repo: bowtie-co/node-selenium-driver
  api_key:
    secure: EtESPkhD1N4be0ULxvqohwiaI3qRCLPqHoSe3reVLqtZ0f/UoLSF9EyygY65NoFqqbGHcOjkmyjRO5m1iBTXsaDKGLyx1+WAvxnnpXC9sjvcpGVDai1JJc68qX9xXtcKoNmxJwq2NPrYzkxfzWRE6JikVCjcyeFXw2LaWYNhWaH6rjliLKkxcV6YZiIC66ozudPOPV3KrXXDn7aTHYJhGCYMm0vdCEB7gRp+MQy6358GF4ajkFSfeulfb32bO2/9gBiuDDnstxRNz42czvDvXGvHotXAY+JeI0g/bkBPPoneJOQmqk/+2ctiyKa2E6xBF2mQjiLBmb8kcDAyb6Sq1PWWXSInJmWrh1gNFnYbj/Xgw44owlz0vP9tBJTlvik/NAJkbp3/e6WVZJ350nWlTzA4vLGRGJe1rj6m2d7htTGLq2YXeXGj5lpsgjTpii7sYdj2PMcq9K3KaT5njSKdILqL+DEks4z+gSkVqdEVWYCQpHMh2RVOij4jkigNZtYtStRQri3071t/dPV3Xzhwen+awbYyK64pm+jx+XMOWKGPpIkNOn/v+Lf582Eo4SvUAZmZhZoYdA+tncHBZUe97BzKBHTm+jeFiUGooqHWDrWAQbkcjBDki1fGE30t500UO8Izx+6iINg5Nho5+hHJYBDWg5MAPfrVy7i88aMMjUk=
notifications:
  slack:
    secure: ETJSnMHwFt1JL3+F18wxkB9VZ21hdA51OxWF/DuL0mhoal+MJsmu5vF0ffm26+dj6R3XZVQ78b+0mlb7Xf+IfBTk2Dm+/GtqgAJu3+D+p88zQMZ4wjytr/RGqEOOqhWLedycg+ggvbHXYoN48LXSLE+Jba/vau56AUhgfOsyAnD4M/qRgm2zlTXI2vqvETGhdqBCN6x8JuX92W3u1q8P3Hd+xcZzqKtq5qAnL5zzZemf2qLvQWhTHSwKbkCWzfPPdd6n3vS6TYE5KzwXcTXFPQT1T4qoqUcKKtPFK9emmigzQlh/i5U5IaFkW8Qs6A0W4U6aNijKHDEiUvTS5GghZyYk6hgOLoa80pJPoDKhQ1vGtESrLDMxDrVSjAtcL2K7LFArWn2JdR75RobMf3ie2/kNTXA+aIpQraS25MX0w2FHNJAFnTrRsTEN3pf4qmGAvfb1ZGjZVODkRbNKgOMceOw5lz3G3/JJsuUt5I7FO7YUJIP1YlZBZzRsEA5Y7ifg0ytA/XXQvGgdmqonAXI77J0v92edaeuzWhz/dUMcN+3XePCDYoibbavoAMbYfBw2wXrYix41Pb5xeFaaWQzKx6ss4elbgcOydqD1BifIY5hKlKA2NzyZC/9Rwkqv1uwy9GhAGL2iUc11nkTfwzNPcEFGLUOFdBizoCy1+50MIE4=
